name: RainWallpaperFX Portable İndir

on:
  workflow_dispatch:

jobs:
  indir:
    runs-on: windows-latest
    steps:
      - name: ZIP Dosyasını İndir
        run: |
          Invoke-WebRequest -Uri "https://github.com/rainwallpaper/rainwallpaperfx/releases/latest/download/RainWallpaperFX.Portable.zip" -OutFile "RainWallpaperFX.zip"

      - name: Artifact Olarak Yükle
        uses: actions/upload-artifact@v4
        with:
          name: RainWallpaperFX-Portable
          path: RainWallpaperFX.zip
          retention-days: 7
