name: Wallpaper Engine Portable İndir ve Paketle

on:
  workflow_dispatch:

jobs:
  indir-ve-paketle:
    runs-on: windows-latest
    steps:
      - name: Unofficial Portable Sürümünü İndir
        run: |
          Invoke-WebRequest -Uri "https://github.com/redknightLOL/WallpaperEngine-Portable/archive/refs/heads/main.zip" -OutFile "WallpaperEngine-Portable.zip"

      - name: ZIP İçeriğini Aç
        run: |
          Expand-Archive -Path "WallpaperEngine-Portable.zip" -DestinationPath ".\extracted"

      - name: Klasör Yapısını Düzenle
        run: |
          $folder = Get-ChildItem -Path ".\extracted" -Directory | Select-Object -First 1
          Move-Item -Path "$($folder.FullName)" -Destination "WallpaperEngine-Portable-Unpacked"

      - name: Tekrar ZIP Yap (Düzgün Klasör Adıyla)
        run: |
          Compress-Archive -Path "WallpaperEngine-Portable-Unpacked\*" -DestinationPath "WallpaperEngine-Portable-Final.zip"

      - name: Sonuçları Yükle
        uses: actions/upload-artifact@v4
        with:
          name: WallpaperEngine-Portable
          path: WallpaperEngine-Portable-Final.zip
          retention-days: 7
